# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(upload_to='profileImg/'),
        ),
    ]
