# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='projectF',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='awardapp.Project'),
        ),
    ]
