# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0002_auto_20191031_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(default='default.jpg', upload_to='profileImg/'),
        ),
    ]
