# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0006_auto_20191031_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
